apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: deploy-ctmag-twcc2
  name: deploy-ctmag-twcc2
spec:
  replicas: 2
  selector:
    matchLabels:
      type: deploy-ctmag-twcc2
  template:
    metadata:
      labels:
        type: deploy-ctmag-twcc2
    spec:
      containers:
      - env:
        - name: AAPI_END_POINT
          value: https://twcc2:8443/automation-api
        - name: AAPI_TOKEN
          valueFrom:
             secretKeyRef:
                name: credentials
                key: AAPI_TOKEN
        - name: AAPI_USER
          value: inpod
        - name: AAPI_PSWD
          valueFrom:
             secretKeyRef:
                name: credentials
                key: AAPI_PSWD 
        - name: AGENT_PORT
          value: "7006"
        - name: SERVER_HOST
          value: ctm920-921-2019en
        - name: CTM_SERVER_NAME
          value: CTM
        - name: PERM_HOSTS
          value: ctm920-921-2019en
        - name: AGENT_HOSTGROUP_NAME
          value: kubetwcc2
        - name: AGENT_TAG
          value: kubetwcc2
        image: ctmag:twcc2
        imagePullPolicy: IfNotPresent
        name: ctmagent-container
        lifecycle:
          preStop:
            exec:
              command: ["/home/ctmag/decommission_controlm.sh"]
      #This is for hostname resolution purpose, if DNS configured not required this specifiction
      hostAliases:
      - hostnames:
        - twcc
        ip: "192.168.211.146" 
      - hostnames:
        - ctm921new2019en
        ip: "192.168.211.146"
       - hostnames:
        - twcc2
        ip: "192.168.211.137"  
       - hostnames:
        - ctm920-921-2019en
        ip: "192.168.211.137"  
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
