apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bmc-ctm-gss              # hpa name  please chane it 
  namespace: your-namespace     # ocp project name
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app                #deployment name
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50