apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-agent-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    type: stateful-service-ctmag-srv
  name: ha-statefulset-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      type: stateful-service-ctmag-srv
  serviceName: ctmag
  template:
    metadata:
      labels:
        type: stateful-service-ctmag-srv
    spec:
      containers:
      - env:
        - name: PERSISTENT_VOL
          value: /home/controlm/persistent_folder
        - name: CTM_SERVER_NAME
          value: CTM
        - name: PERM_HOSTS
          value: 9-19
        - name: AGENT_HOSTGROUP_NAME
          value: kube
        image: ctmag:920200cm
        imagePullPolicy: IfNotPresent
        name: ctmagent-container
        ports:
        - containerPort: 7006
        volumeMounts:
        - mountPath: /home/controlm/persistent_folder
          name: pv-data
      hostAliases:
      - hostnames:
        - 9-19
        ip: 192.168.206.129
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 10
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: ha-agent-pvc
