apiVersion: batch/v1
kind: Job
metadata:
  name: echojob
spec:
  template:
    metadata:
        name: echojob
        labels: {
           app: controlm,
           controlm-order-id-internal-label : echojob
        }     

    spec:
      containers:
      - name: almalinux8
        image: almalinux:8
        command: [ "echo", "{{job_yaml_file_params:masterid}}" ]
      restartPolicy: Never
      
