apiVersion: v1
kind: PersistentVolume
metadata:
  name: uobpv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /srv/uobpv
    server: k8smaster
